<?php

namespace Drupal\webform_strawberryfield\Element;

use Drupal\webform\Element\WebformManagedFileBase;

/**
 * Provides a webform element for an 'document_file' element.
 *
 * @FormElement("webform_metadata_csv_file")
 */
class WebformMetadataCsvFile extends WebformManagedFileBase {

  public function getInfo() {
    return parent::getInfo(); // TODO: Change the autogenerated stub
  }


}
